# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:

  email_provider_username: <%= ENV["AasishSharma"] %>
  email_provider_password: <%= ENV["rm13as91"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["f5acb3eecaa022f27b5d220317f6879a-us13"] %>
  mailchimp_list_id: <%= ENV["2e3643d203"] %>
  owner_email: <%= ENV["aasish@rubyeffect.com"] %>
  secret_key_base: a8a6664a9f06aaf683695717bdee35a4a017ec1213dbc0f9301fd3085e1d98ea8fd15b78dbea05ff3d6117fa0b65f206f21cb56ae4a663fb33feb17ed5c15c52


test:
  
  secret_key_base: a8a6664a9f06aaf683695717bdee35a4a017ec1213dbc0f9301fd3085e1d98ea8fd15b78dbea05ff3d6117fa0b65f206f21cb56ae4a663fb33feb17ed5c15c52


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

  email_provider_username: <%= ENV["AasishSharma"] %>
  email_provider_password: <%= ENV["rm13as91"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["f5acb3eecaa022f27b5d220317f6879a-us13"] %>
  mailchimp_list_id: <%= ENV["2e3643d203"] %>
  owner_email: <%= ENV["aasish@rubyeffect.com"] %>
  secret_key_base: <%= ENV["a8a6664a9f06aaf683695717bdee35a4a017ec1213dbc0f9301fd3085e1d98ea8fd15b78dbea05ff3d6117fa0b65f206f21cb56ae4a663fb33feb17ed5c15c52"] %>