
development:

  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_password: <%= ENV["MANDRILL_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: b4da83d0f5b5b7a3fc1d766f33e9f668c6cc72aa342ceb1f5909c049c335cb76cdce1a2edd8154f4730a50d7e1d355c62a3611912edc477752dcff13cabe2f29

test:
  
  secret_key_base: b4da83d0f5b5b7a3fc1d766f33e9f668c6cc72aa342ceb1f5909c049c335cb76cdce1a2edd8154f4730a50d7e1d355c62a3611912edc477752dcff13cabe2f29

production:

  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_password: <%= ENV["MANDRILL_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

